### ISSUE TITLE
BFC规则和利用

### ISSUE THREAD

**Issue by Daemon1216** [Daemon1216/blog#4]
#### BFC 是什么

BFC(Block-level Formatting Context): 块格式化上下文。它是一个独立的渲染区域，只有 Block-level box 参与， 它规定了内部的 Block-level Box 如何布局，并且与这个区域外部毫不相干。

- Box-level：块级元素
- Formatting context
  > Formatting context 是 W3C CSS2.1 规范中的一个概念。它是页面中的一块渲染区域，并且有一套渲染规则，它决定了其子元素将如何定位，以及和其他元素的关系、相互作用。最常见的 Formatting context 有 Block fomatting context (简称 BFC)和 Inline formatting context(简称 IFC)。

> CSS2.1 中只有 BFC 和 IFC, CSS3 中还增加了 G（grid）FC 和 F(flex)FC。

#### BFC 生成

1. 根元素(html)
2. 浮动元素（元素的 float 不是 none）
3. 绝对定位元素（元素的 position 为 absolute 或 fixed）
4. overflow 值不为 visible 的块元素
5. display 值为 inline-block、flow-root 的元素
6. 表格和弹性、网格元素等

#### BFC 布局规则

1. 内部的 Box 会在垂直方向上一个接一个的放置
2. 属于同一个 BFC 的两个相邻 Box 的 margin 会发生重叠（塌陷）
3. 每个元素的左外边距与包含块的左边界相接触（从左向右），即使浮动元素也是如此。（这说明 BFC 中子元素不会超出他的包含块，而 position 为 absolute 的元素可以超出他的包含块边界）
4. BFC 的区域不会与外部的 float 元素区域重叠
5. 计算 BFC 的高度时，浮动子元素也参与计算
6. **BFC 就是页面上的一个隔离的独立容器，容器里面的子元素不会影响到外面元素，反之亦然**

#### BFC 应用

1. 利用 BFC 闭合浮动
   > 计算 BFC 的高度时，浮动元素也参与计算

```css
.container {
  border: 2px solid pink;
  overflow: hidden;
}
.content {
  float: left;
  width: 100px;
  height: 100px;
  background: lightgreen;
}
```

经典方法：利用伪元素

```css
.clearfix:after {
  content: ".";
  display: "block";
  height: 0;
  visibility: hidden;
  clear: both;
}
.clearfix {
  *zoom: 1;
}
```

2. 自适应两（多）栏布局
   > 每个元素的左外边距与包含块的左边界相接触（从左向右），即使浮动元素也是如此。
   > 根据 BFC 布局规则第 4 条：
   > BFC 的区域不会与外部 float box 重叠。

- 自适应两栏布局: float 和 BFC

```css
.left {
  float: left;
  width: 100px;
  height: 100px;
  background: pink;
}
.right {
  overflow: hidden;
  height: 100px;
  background: lightgreen;
}
```

- 两侧固定，中间自适应
  > 缺点：主体内容最后加载

```css
<style>
  .container>div{
    height: 200px;
  }
  .left {
    float: left;
    width: 300px;
    background: pink;
  }
  .right {
    float: right;
    width: 300px;
    background: ligthgreen;
  }
  .center {
    overflow: hidden;
    background: lightyellow;
  }
</style>
```

```html
<div class="container">
  <div class="left"></div>
  <div class="right"></div>
  <div class="center"></div>
</div>
```
