### ISSUE TITLE
经典布局问题

### ISSUE THREAD

**Issue by Daemon1216** [Daemon1216/blog#5]
# 圣杯布局

> 缺点就是处理复杂，而且当中间元素小于两侧元素时候会出现变形，响应效果相对差一点。

1. container padding 解决center实际上被left/right遮挡的问题；left/right为relative定位
```css
<style>
  .container>div{
    height: 200px;
  }
  .container{
    padding: 0 100px;
  }
  .left {
    float: left;
    width: 100px;
    background: pink;
    margin-left: -100%;
    position: relative;
    left: -100px;
  }
  .right {
    float: left;
    width: 100px;
    background: lightgreen;
    margin-left: -100px;
    position: relative;
    right: -100px;
  }
  .center {
    float: left;
    width: 100%;
    background: lightyellow;
  }
</style>
```
```html
<div class="container">
    <div class="center"></div>
    <div class="left"></div>
    <div class="right"></div>
</div>
```

# 双飞翼布局

> 相比圣杯布局更简洁，多使用了一个 div，不过简洁性和响应能力上要比圣杯布局好。

center margin解决center实际上被left/right遮挡的问题
```css
<style>
  .container div{
    height: 200px;
  }
  .left {
    float: left;
    width: 100px;
    background: pink;
    margin-left: -100%;
  }
  .right {
    float: left;
    width: 100px;
    background: lightgreen;
    margin-left: -100px;
  }
  .center-wrap {
    float: left;
    width: 100%;
    background: lightyellow;
  }
  .center {
    margin: 0 100px;
  }
</style>
```
```html
<div class="container">
    <div class="center-wrap">
        <div class="center"></div>
    </div>
    <div class="left"></div>
    <div class="right"></div>
</div>
```

# flex 布局

#### [flex](https://zhuanlan.zhihu.com/p/25303493)

flex 容器的属性：

1. flex-direction(主轴方向): row | row-reverse | column | column-reverse;
2. flex-wrap(容器内项目是否可换行): nowrap | wrap | wrap-reverse;
3. flex-flow: flex-direction 和 flex-wrap 的简写形式
4. **justify-content**(定义了项目在主轴的对齐方式): flex-start | flex-end | center | space-between | space-around;
5. **align-items**(定义了项目在交叉轴上的对齐方式): flex-start | flex-end | center | baseline | stretch;
6. align-content(定义了多根轴线的对齐方式，如果项目只有一根轴线，那么该属性将不起作用): flex-start | flex-end | center | space-between | space-around | stretch;

Flex 项目属性：

1. order(定义项目在容器中的排列顺序，数值越小越前)
2. flex-basis
3. flex-grow
4. flex-shrink
5. **flex**(flex-grow, flex-shrink 和 flex-basis 的简写)：子容器根据 flex 定义的比例尺寸自动伸缩
6. **align-self**(允许单个项目有与其他项目不一样的对齐方式)

> 唯一的问题就是旧浏览器不兼容这一布局方式

```css
<style type="text/css">
  .container {
    display: flex;
  }
  .container>div {
    height: 200px;
  }
  .left {
    width: 100px;
    background: pink;
  }
  .center {
    flex: 1;
    background: lightyellow;
  }
  .right {
    width: 100px;
    background: lightgreen;
  }
</style>
```
```html
<div class="container">
  <div class="left">左侧</div>
  <div class="center">中间</div>
  <div class="right">右侧</div>
</div>
```

# grid 布局

> 缺点：兼容性问题

```css
.container {
  display: grid;
  width: 100%;
  grid-template-rows: 200px;
  grid-template-columns: 300px auto 300px;
}
.left {
  background: pink;
}
.center {
  background: lightyellow;
}
.right {
  background: lightgreen;
}
```
```html
<div class="container">
  <div class="left"></div>
  <div class="center"></div>
  <div class="right"></div>
</div>
```
