### ISSUE TITLE
垂直水平居中

### ISSUE THREAD

**Issue by Daemon1216** [Daemon1216/blog#6]
#### position 定位

1. 利用 absolute 的流体特性实现垂直水平居中

对立方向同时发生定位，导致流体特性出现，宽度自适应于包含块的 padding 盒子宽度；margin: auto 再把上下左右剩余空间全部等分。

```css
.content {
  position: absolute;
  top: 0;
  right: 0;
  bottom: 0;
  left: 0;
  width: 200px;
  height: 100px;
  margin: auto;
}
```

2. 利用 absolute 的包裹性(包裹和自适应)实现水平垂直居中

单侧方向定位，absolute 元素表现为包裹性。

> 缺点：由于设置了 left、top 的百分比，content 元素的自适应最大宽度不得超过 50%，也就是明明还有可适应的空间，他却自动换行了。

- absolute 元素定宽高

```css
.content {
  position: absolute;
  left: 50%;
  top: 50%;
  height: 100px;
  width: 100px;
  background-color: pink;
  margin-left: -50px; // content定宽的前提下, 1/2*width
  margin-top: -50px; // content定高的前提下, 1/2*height
}
```

- 在 absolute 元素外包裹 div

```css
div {
  position: absolute;
  left: 50%;
  top: 50%;
}
.content {
  position: absolute;
  width: 100px;
  height: 100px;
  background-color: pink;
  margin-left: -50%;
  margin-top: -50%;
}
```

- css3 特性，有 ie 兼容性问题

```css
.content {
  position: absolute;
  top: 50%;
  left: 50%;
  width: 100px;
  height: 100px;
  background-color: pink;
  transform: translate(-50%, -50%);
}
```

#### flex 布局

```css
.container {
  display: flex;
  justify-content: center; /* 水平居中 */
  align-items: center; /* 垂直居中 */
  height: 200px;
  width: 200px;
  background: pink;
}
.content {
  width: 100px;
  height: 100px;
  background: lightgreen;
}
```

```html
<div class="container">
  <div class="content">test</div>
</div>
```

#### 水平居中

1. text-align 实现水平居中

```css
.container {
  width: 100px;
  height: 100px;
  background-color: lightgreen;
  text-align: center;
}
```

#### 垂直居中

2. 一行行内元素：line-height，利用行距的上下等分机制

```css
.container {
  width: 100px;
  height: 100px; /* 可以不设 */
  background: lightgreen;
  line-height: 100px; /* 垂直居中 */
}
```

3. 多行或者图片等替换元素：line-height 和 vertical-align(行内元素相对于父元素垂直对齐)

> 实现原理：
设置 .content 元素的 display 为 inline-block。作用在于既能重置外部的 line-height 为正常大小，又能保持行内元素特性，从而可以设置 vertical-align 属性，以及产生一个非常关键的“行框盒子”。我们需要的其实并不是这个“行框盒子”，而是每个“行框盒子”都会附带的一个产物 —— “幽灵空白节点”，即一个宽度为 0，表现如同普通字符的看不见的“节点”。有了这个“幽灵空白节点”，我们的 line-height: 300px; 就有了作用的对象，从而相当于在 .content 元素前面撑起了一个高度为 300px 的宽度为 0 的行内元素。

```css
.container {
  width: 300px;
  background-color: pink;
  line-height: 300px;
}

.content {
  display: inline-block;
  background-color: lightyellow;
  color: lightgreen;
  line-height: 20px;
  vertical-align: middle;
}
```

```html
<div class="container">
  <span class="content">
    我是要居中的行内元素span <br />
    我是要居中的行内元素span
  </span>
</div>
```
